// Defines for ATmega48A/PA/88A/PA/168A/PA/328/P.
// Autogenerated by pin-defines v0.0.1
// Updated: Tue Aug 12 2014 18:14:33 GMT-0400 (EDT)

#include <avr/io.h>

#define EEPROM_CS_DDR        DDRD
#define EEPROM_CS_PORT       PORTD
#define EEPROM_CS_PIN        PIND
#define EEPROM_CS_MASK       (1 << 2)

#define EEPROM_CS_ToOutput() (EEPROM_CS_DDR |= EEPROM_CS_MASK)
#define EEPROM_CS_ToInput()  (EEPROM_CS_DDR &= ~EEPROM_CS_MASK)

#define EEPROM_CS_High()     (EEPROM_CS_PORT |= EEPROM_CS_MASK)
#define EEPROM_CS_Low()      (EEPROM_CS_PORT &= ~EEPROM_CS_MASK)

#define EEPROM_CS_Read()     ((EEPROM_CS_PIN & EEPROM_CS_MASK) != 0)
#define EEPROM_CS_IsLow()    (!EEPROM_CS_Read())
#define EEPROM_CS_IsHigh()   (EEPROM_CS_Read())

#define EEPROM_CS_LoopUntilHigh() do { } while (EEPROM_CS_IsLow())
#define EEPROM_CS_LoopUntilLow()  do { } while (EEPROM_CS_IsHigh())

#define RED_LED_DDR        DDRC
#define RED_LED_PORT       PORTC
#define RED_LED_PIN        PINC
#define RED_LED_MASK       (1 << 1)

#define RED_LED_ToOutput() (RED_LED_DDR |= RED_LED_MASK)
#define RED_LED_ToInput()  (RED_LED_DDR &= ~RED_LED_MASK)

#define RED_LED_High()     (RED_LED_PORT |= RED_LED_MASK)
#define RED_LED_Low()      (RED_LED_PORT &= ~RED_LED_MASK)

#define RED_LED_Read()     ((RED_LED_PIN & RED_LED_MASK) != 0)
#define RED_LED_IsLow()    (!RED_LED_Read())
#define RED_LED_IsHigh()   (RED_LED_Read())

#define RED_LED_LoopUntilHigh() do { } while (RED_LED_IsLow())
#define RED_LED_LoopUntilLow()  do { } while (RED_LED_IsHigh())

#define YLW_LED_DDR        DDRC
#define YLW_LED_PORT       PORTC
#define YLW_LED_PIN        PINC
#define YLW_LED_MASK       (1 << 2)

#define YLW_LED_ToOutput() (YLW_LED_DDR |= YLW_LED_MASK)
#define YLW_LED_ToInput()  (YLW_LED_DDR &= ~YLW_LED_MASK)

#define YLW_LED_High()     (YLW_LED_PORT |= YLW_LED_MASK)
#define YLW_LED_Low()      (YLW_LED_PORT &= ~YLW_LED_MASK)

#define YLW_LED_Read()     ((YLW_LED_PIN & YLW_LED_MASK) != 0)
#define YLW_LED_IsLow()    (!YLW_LED_Read())
#define YLW_LED_IsHigh()   (YLW_LED_Read())

#define YLW_LED_LoopUntilHigh() do { } while (YLW_LED_IsLow())
#define YLW_LED_LoopUntilLow()  do { } while (YLW_LED_IsHigh())

#define GRN_LED_DDR        DDRC
#define GRN_LED_PORT       PORTC
#define GRN_LED_PIN        PINC
#define GRN_LED_MASK       (1 << 5)

#define GRN_LED_ToOutput() (GRN_LED_DDR |= GRN_LED_MASK)
#define GRN_LED_ToInput()  (GRN_LED_DDR &= ~GRN_LED_MASK)

#define GRN_LED_High()     (GRN_LED_PORT |= GRN_LED_MASK)
#define GRN_LED_Low()      (GRN_LED_PORT &= ~GRN_LED_MASK)

#define GRN_LED_Read()     ((GRN_LED_PIN & GRN_LED_MASK) != 0)
#define GRN_LED_IsLow()    (!GRN_LED_Read())
#define GRN_LED_IsHigh()   (GRN_LED_Read())

#define GRN_LED_LoopUntilHigh() do { } while (GRN_LED_IsLow())
#define GRN_LED_LoopUntilLow()  do { } while (GRN_LED_IsHigh())

#define DHT11_DDR        DDRB
#define DHT11_PORT       PORTB
#define DHT11_PIN        PINB
#define DHT11_MASK       (1 << 6)

#define DHT11_ToOutput() (DHT11_DDR |= DHT11_MASK)
#define DHT11_ToInput()  (DHT11_DDR &= ~DHT11_MASK)

#define DHT11_High()     (DHT11_PORT |= DHT11_MASK)
#define DHT11_Low()      (DHT11_PORT &= ~DHT11_MASK)

#define DHT11_Read()     ((DHT11_PIN & DHT11_MASK) != 0)
#define DHT11_IsLow()    (!DHT11_Read())
#define DHT11_IsHigh()   (DHT11_Read())

#define DHT11_LoopUntilHigh() do { } while (DHT11_IsLow())
#define DHT11_LoopUntilLow()  do { } while (DHT11_IsHigh())

#define IRLED_DDR        DDRD
#define IRLED_PORT       PORTD
#define IRLED_PIN        PIND
#define IRLED_MASK       (1 << 3)

#define IRLED_ToOutput() (IRLED_DDR |= IRLED_MASK)
#define IRLED_ToInput()  (IRLED_DDR &= ~IRLED_MASK)

#define IRLED_High()     (IRLED_PORT |= IRLED_MASK)
#define IRLED_Low()      (IRLED_PORT &= ~IRLED_MASK)

#define IRLED_Read()     ((IRLED_PIN & IRLED_MASK) != 0)
#define IRLED_IsLow()    (!IRLED_Read())
#define IRLED_IsHigh()   (IRLED_Read())

#define IRLED_LoopUntilHigh() do { } while (IRLED_IsLow())
#define IRLED_LoopUntilLow()  do { } while (IRLED_IsHigh())

#define NRF24_CE_DDR        DDRC
#define NRF24_CE_PORT       PORTC
#define NRF24_CE_PIN        PINC
#define NRF24_CE_MASK       (1 << 3)

#define NRF24_CE_ToOutput() (NRF24_CE_DDR |= NRF24_CE_MASK)
#define NRF24_CE_ToInput()  (NRF24_CE_DDR &= ~NRF24_CE_MASK)

#define NRF24_CE_High()     (NRF24_CE_PORT |= NRF24_CE_MASK)
#define NRF24_CE_Low()      (NRF24_CE_PORT &= ~NRF24_CE_MASK)

#define NRF24_CE_Read()     ((NRF24_CE_PIN & NRF24_CE_MASK) != 0)
#define NRF24_CE_IsLow()    (!NRF24_CE_Read())
#define NRF24_CE_IsHigh()   (NRF24_CE_Read())

#define NRF24_CE_LoopUntilHigh() do { } while (NRF24_CE_IsLow())
#define NRF24_CE_LoopUntilLow()  do { } while (NRF24_CE_IsHigh())

#define NRF24_CSN_DDR        DDRC
#define NRF24_CSN_PORT       PORTC
#define NRF24_CSN_PIN        PINC
#define NRF24_CSN_MASK       (1 << 4)

#define NRF24_CSN_ToOutput() (NRF24_CSN_DDR |= NRF24_CSN_MASK)
#define NRF24_CSN_ToInput()  (NRF24_CSN_DDR &= ~NRF24_CSN_MASK)

#define NRF24_CSN_High()     (NRF24_CSN_PORT |= NRF24_CSN_MASK)
#define NRF24_CSN_Low()      (NRF24_CSN_PORT &= ~NRF24_CSN_MASK)

#define NRF24_CSN_Read()     ((NRF24_CSN_PIN & NRF24_CSN_MASK) != 0)
#define NRF24_CSN_IsLow()    (!NRF24_CSN_Read())
#define NRF24_CSN_IsHigh()   (NRF24_CSN_Read())

#define NRF24_CSN_LoopUntilHigh() do { } while (NRF24_CSN_IsLow())
#define NRF24_CSN_LoopUntilLow()  do { } while (NRF24_CSN_IsHigh())

