// Defines for ATmega48A/PA/88A/PA/168A/PA/328/P.
// Autogenerated by pin-defines v0.0.1
// Updated: Sun Aug 17 2014 16:53:49 GMT-0400 (EDT)

#include <avr/io.h>

#define FLASH_CS_DDR        DDRD
#define FLASH_CS_PORT       PORTD
#define FLASH_CS_PIN        PIND
#define FLASH_CS_MASK       (1 << 2)

#define FLASH_CS_ToOutput() (FLASH_CS_DDR |= FLASH_CS_MASK)
#define FLASH_CS_ToInput()  (FLASH_CS_DDR &= ~FLASH_CS_MASK)

#define FLASH_CS_High()     (FLASH_CS_PORT |= FLASH_CS_MASK)
#define FLASH_CS_Low()      (FLASH_CS_PORT &= ~FLASH_CS_MASK)

#define FLASH_CS_Read()     ((FLASH_CS_PIN & FLASH_CS_MASK) != 0)
#define FLASH_CS_IsLow()    (!FLASH_CS_Read())
#define FLASH_CS_IsHigh()   (FLASH_CS_Read())

#define FLASH_CS_LoopUntilHigh() do { } while (FLASH_CS_IsLow())
#define FLASH_CS_LoopUntilLow()  do { } while (FLASH_CS_IsHigh())

#define RED_LED_DDR        DDRC
#define RED_LED_PORT       PORTC
#define RED_LED_PIN        PINC
#define RED_LED_MASK       (1 << 1)

#define RED_LED_ToOutput() (RED_LED_DDR |= RED_LED_MASK)
#define RED_LED_ToInput()  (RED_LED_DDR &= ~RED_LED_MASK)

#define RED_LED_High()     (RED_LED_PORT |= RED_LED_MASK)
#define RED_LED_Low()      (RED_LED_PORT &= ~RED_LED_MASK)

#define RED_LED_Read()     ((RED_LED_PIN & RED_LED_MASK) != 0)
#define RED_LED_IsLow()    (!RED_LED_Read())
#define RED_LED_IsHigh()   (RED_LED_Read())

#define RED_LED_LoopUntilHigh() do { } while (RED_LED_IsLow())
#define RED_LED_LoopUntilLow()  do { } while (RED_LED_IsHigh())

#define YLW_LED_DDR        DDRC
#define YLW_LED_PORT       PORTC
#define YLW_LED_PIN        PINC
#define YLW_LED_MASK       (1 << 2)

#define YLW_LED_ToOutput() (YLW_LED_DDR |= YLW_LED_MASK)
#define YLW_LED_ToInput()  (YLW_LED_DDR &= ~YLW_LED_MASK)

#define YLW_LED_High()     (YLW_LED_PORT |= YLW_LED_MASK)
#define YLW_LED_Low()      (YLW_LED_PORT &= ~YLW_LED_MASK)

#define YLW_LED_Read()     ((YLW_LED_PIN & YLW_LED_MASK) != 0)
#define YLW_LED_IsLow()    (!YLW_LED_Read())
#define YLW_LED_IsHigh()   (YLW_LED_Read())

#define YLW_LED_LoopUntilHigh() do { } while (YLW_LED_IsLow())
#define YLW_LED_LoopUntilLow()  do { } while (YLW_LED_IsHigh())

#define GRN_LED_DDR        DDRC
#define GRN_LED_PORT       PORTC
#define GRN_LED_PIN        PINC
#define GRN_LED_MASK       (1 << 5)

#define GRN_LED_ToOutput() (GRN_LED_DDR |= GRN_LED_MASK)
#define GRN_LED_ToInput()  (GRN_LED_DDR &= ~GRN_LED_MASK)

#define GRN_LED_High()     (GRN_LED_PORT |= GRN_LED_MASK)
#define GRN_LED_Low()      (GRN_LED_PORT &= ~GRN_LED_MASK)

#define GRN_LED_Read()     ((GRN_LED_PIN & GRN_LED_MASK) != 0)
#define GRN_LED_IsLow()    (!GRN_LED_Read())
#define GRN_LED_IsHigh()   (GRN_LED_Read())

#define GRN_LED_LoopUntilHigh() do { } while (GRN_LED_IsLow())
#define GRN_LED_LoopUntilLow()  do { } while (GRN_LED_IsHigh())

#define NRF24_CE_DDR        DDRC
#define NRF24_CE_PORT       PORTC
#define NRF24_CE_PIN        PINC
#define NRF24_CE_MASK       (1 << 3)

#define NRF24_CE_ToOutput() (NRF24_CE_DDR |= NRF24_CE_MASK)
#define NRF24_CE_ToInput()  (NRF24_CE_DDR &= ~NRF24_CE_MASK)

#define NRF24_CE_High()     (NRF24_CE_PORT |= NRF24_CE_MASK)
#define NRF24_CE_Low()      (NRF24_CE_PORT &= ~NRF24_CE_MASK)

#define NRF24_CE_Read()     ((NRF24_CE_PIN & NRF24_CE_MASK) != 0)
#define NRF24_CE_IsLow()    (!NRF24_CE_Read())
#define NRF24_CE_IsHigh()   (NRF24_CE_Read())

#define NRF24_CE_LoopUntilHigh() do { } while (NRF24_CE_IsLow())
#define NRF24_CE_LoopUntilLow()  do { } while (NRF24_CE_IsHigh())

#define NRF24_CSN_DDR        DDRC
#define NRF24_CSN_PORT       PORTC
#define NRF24_CSN_PIN        PINC
#define NRF24_CSN_MASK       (1 << 4)

#define NRF24_CSN_ToOutput() (NRF24_CSN_DDR |= NRF24_CSN_MASK)
#define NRF24_CSN_ToInput()  (NRF24_CSN_DDR &= ~NRF24_CSN_MASK)

#define NRF24_CSN_High()     (NRF24_CSN_PORT |= NRF24_CSN_MASK)
#define NRF24_CSN_Low()      (NRF24_CSN_PORT &= ~NRF24_CSN_MASK)

#define NRF24_CSN_Read()     ((NRF24_CSN_PIN & NRF24_CSN_MASK) != 0)
#define NRF24_CSN_IsLow()    (!NRF24_CSN_Read())
#define NRF24_CSN_IsHigh()   (NRF24_CSN_Read())

#define NRF24_CSN_LoopUntilHigh() do { } while (NRF24_CSN_IsLow())
#define NRF24_CSN_LoopUntilLow()  do { } while (NRF24_CSN_IsHigh())

